server:
  port: 9998

spring:
  application:
    name: market-watch-backend-service
  datasource:
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/market_watch
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
